### ISSUE TITLE
Create Demo Application

### ISSUE THREAD

**Issue by Slion** [Lakritzator/harmony#8]
I'm working on a small Windows Forms application.

**Comment by Lakritzator** [comment]
Cool!

And I was working, for some time now (pretty much since I started the fork), on a MVVM based WPF application which hangs around in the system tray. The work stopped due to some issues with the library, and other work on Greenshot.

This was one of the reasons I needed the harmony API to be async based, so my UI doesn't hang.

But I think both make sense!!! And knowing me, it's never finished, which was why I wanted to have my changes finished as soon as possible so I am not annoyed by me having something half finished.

Over the next week(s) I will make it run with some basics and push it somewhere 😄 
I'm curious about your demo!

**Comment by Slion** [comment]
It's just a very basic app for testing our HarmonyHub library without having to use the command line tool. I'm pushing it now.

**Comment by Slion** [comment]
Here is the Pull Request https://github.com/Lakritzator/harmony/pull/9
You can double click on commands to send them.

**Comment by Lakritzator** [comment]
Very cool, merged and closing the ticket.

It might be cool if you added a "notice" to explain how to use it to the users...
Without the last line in your previous comment I wouldn't have known.
